<?php
/**
 * Created by PhpStorm.
 * User: zhanghongbo
 * Date: 2019/3/13
 * Time: 上午11:38
 */
namespace api\Modules\v1;

use yii\base\BootstrapInterface;

class Module extends \yii\base\Module implements BootstrapInterface
{
    public $controllerNamespace = 'admin\api\Modules\v1\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function bootstrap($app)
    {
        $app->getUrlManager()->addRules([
           [
               'class' => 'yii\rest\UrlRule',
               'controller' => ['v1/furniture'],
               'extraPatterns' => [
                   'PUT update' => 'update',
               ],
               'pluralize' => false,
           ],
            'GET,POST,PUT,HEAD v1/<controller>/<action>' => 'v1/<controller>/<action>',
            'GET,POST,PUT,HEAD v1/<controller:\w+>/<action>/<id:\d+>' => 'v1/<controller>/<action>',
        ]);
    }
}